"""
********************************************************************************************
* manage.py                        |********************************************************
* Developed by: Ryan Hatch         |********************************************************
* Date: August 10th 2022           |********************************************************
* Last Updated: Febuary 13th 2025  |********************************************************
* Version: 6.2.2-A                 |********************************************************
********************************************************************************************
********************************#* Description: |*******************************************
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
|  manage.py is a module that contains the database models for the web-app.                *
*    SQLite / SQLAlchemy to define the models and their relationships. The models are:     *
*       - User: stores the user information.                                               *
*       - Hash: stores the hashes generated by the user.                                   *
*       - EncryptedText: stores the encrypted texts generated by the user.                 *
*       - Key: stores the keys generated by the user.                                      *
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
********************************************************************************************
"""

#* ---------------------- | Import libraries for the web-app | ---------------------- *#
from flask import Flask
from flask_migrate import Migrate
from models import db, User, Hash, EncryptedText, Key, PGPKey

#* Importing the required libraries for the webapp
from flask import Flask, request, render_template_string, redirect, url_for, session, jsonify, send_from_directory
from flask_sqlalchemy import SQLAlchemy
from flask_jwt_extended import JWTManager, create_access_token, jwt_required, get_jwt_identity
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import serialization
from werkzeug.security import generate_password_hash, check_password_hash

import hashlib
import os
import base64
import secrets
from datetime import timedelta
from dotenv import load_dotenv
from utils import generate_pgp_keypair, pgp_encrypt_message, pgp_decrypt_message, generate_hash, encrypt_text, decrypt_text, encrypt_file, decrypt_file

#* ---------------------- | Initialize merge | ---------------------- *#
app = Flask(__name__) # Initialize the Flask app
#* Load the environment variables
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///zencrypt.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db.init_app(app)            # Initialize the database
migrate = Migrate(app, db)  # Initialize the migration

#* Run the web-apps migrations
if __name__ == '__main__':
    app.run()
