services:
  - type: web
    name: zencrypt
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn webapp:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
    services:
      - type: mongodb
        name: zencrypt-db
        ipAllowList: []